### ISSUE TITLE
サイドバーは日本語にできない

### ISSUE THREAD

**Issue by sgk** [SWITCHSCIENCE/arduinohistory.github.io#2]
サイドバーは、`_includes/sidebar.html`にあり、全ページで共通。

**Comment by bhagman** [comment]
Hey guys - a suggestion/idea

Copy the `default.html` layout (in `_layouts`) to `ja.html`, then use that as the layout for `ja.md`.

Then you can either add the index section directly to `_layouts/ja.html` or add a new `_includes/sidebar-ja.html` and include it.

Sorry about the kludge of adding the Index in the sidebar.  :(

**Comment by sgk** [comment]
9682afed7cee21e57985331a663e1945a380d5d0
