### ISSUE TITLE
ページ上部のタイトルの表示が日本語にできない

### ISSUE THREAD

**Issue by sgk** [SWITCHSCIENCE/arduinohistory.github.io#3]
`_layouts/default.html`で、`{{ site.title }}`と記述されているため、全体で共通。

**Comment by bhagman** [comment]
Same solution as #2 , but instead, change `_layouts/ja.html` to use `site.title-ja` from `_config.yml`, and add the title there.

Similarly, `_includes/head-ja.html` will need to be added, and refer to `site.title-ja` from `_config.yml`.

Do you agree?

I can help you guys with this, if you'd like.  Let me know.

**Comment by sgk** [comment]
Thank you for your advise! I did not expect comments from others outside of our team. Do you read the Japanese texts?

I agree to the solutions, and try to do them. Thank you.

**Comment by sgk** [comment]
97d30e6401cf84d73ea15235ce822479b10baaff
